var overview_page_1 = "     Project Perfect Citizen - Employee Manual\n\nWelcome, compatriot! You've made a great choice in joining the fight against the insecurity. This handbook will be your guide to the world of the SecureNetwork.\
\n\n              TABLE OF CONTENTS\n\nOverview\n    Table of Contents\n    Your Role as a Public Defender\n    The Basics: Types of Data\n    The Basics: Metadata\
\n\nHistory\n    What is Project Perfect Citizen?\
\n\nExample\n    An Example of Your Daily Work: The Pipeline\n    An Example of Your Daily Work: Apprehension\n    An Example of Your Daily Work: Permission\
\n\nReference\n    DATA REFERENCE\n    METADATA REFERENCE\n    SAFETY/SECURITY REFERENCE\n    CONSOLE COMMAND REFERENCE";
var overview_page_2 = "Your Role as a Public Defender \n\nDuring your time with Perfect Citizen, you have the honor of apprehending our nation's most vile criminals in order to help secure the future of our digital landscape. Detecting discrepancies in the data of our citizens is one example of the many duties you will perform during Project Perfect Citizen. By opening the SecureNetwork 'pipeline' in your terminal log, you'll be exposed to a rapid series of data that you'll only have a short time to decypher.\
But don't worry, we'll make sure you're trained to handle even the most cunning of cyber terrorist tricks!";
var overview_page_3 = "The Basics: Types of Data\n\nSince the birth of technology, our kind has found many interesting ways of communicating and sharing information with one another. During the course of defending this great nation of ours, you will be exposed to a variety of different information. These include:\n\
\n1)Short Media/Multi-media Text Messages\n\n2)Internet Email Messages\n\n3)Internet Search Engine Queries\n\n4)Phone Conversations\n\n5)Text,Image, and Video File Transfers\n\nPlease see the reference tab for a detailed list of these kinds of information.";
var overview_page_4 = "The Basics: Metadata \n\n Now that we have learned about the kinds of data, allow us to move onto how this data is represented. All information passed through the SecureNetwork is represented as metadata, a list of very abstract fields corresponding to an accurate representation of the information itself. Metadata fields make up data and are also what distinguishes certain data between other data.\
 Please see the corresponding reference section at the back of this handbook for a description of each kind of metadata and the associated metadata fields.";

var history_page_1 = "        WHAT IS PROJECT PERFECT CITIZEN? \n\nA glorious question! Project Perfect Citizen is the first extensive corrections program initiated by the Ministry of Security tasked with the job of detecting and eradicating cyber criminal threats within our great nation's network. This network, the SecureNetwork, is a series of interconnected links between every electronic telecommunications device internationally that controls the channels through which information is passed on.";
var history_page_2 = "\n\n\n\n\n\n\n\n\n\n\n THIS PAGE REQUIRES ADDITIONAL PERMISSIONS TO VIEW";
var history_page_3 = "\n\n\n\n\n\n\n\n\n\n\n THIS PAGE REQUIRES ADDITIONAL PERMISSIONS TO VIEW";
var history_page_4 = "\n\n\n\n\n\n\n\n\n\n\n THIS PAGE REQUIRES ADDITIONAL PERMISSIONS TO VIEW";
    			
var example_page_1 = "An Example of Your Daily Work: The Pipeline\n\n Looks like you're ready to start doing some work! In order to do so, you'll need to open the pipeline to the SecureNetwork stream. \
Open up the pipeline by entering the command\n\n               begin extraction\n\nin your console log. But make sure you're ready! The pipeline can only stay open for a small period of time as to prevent security leaks. \
You will be prompted by a stream of loading text followed by your first piece of data represented in the form of its metadata. An example output may look something like this:\n\n"+ "---------------------------------------------\n---------------------------------------------\n"+
"           CNP: 144.250.183.162\n\n"+"                  QUERY\n"+"{\n\n"+"user_address: johnomaley@secureubc.com\n\n"+"raw_text: 'how to send someone a virus and not get caught'\n\n"+"carrier_address: @secureubc\n\n"+
"}\n"+"---------------------------------------------\n---------------------------------------------\n\n"+"On the top, you'll notice the Citizen Network Protocol (CNP). This is unique to each citizen's electronic platform and will be associated with all passing data of that citizen. Next, you might notice the items between the curly braces. This is the metadata associated with this piece of information. Checking the reference page, you'll notice this is a Search Engine Query.\
 We can verify this by noting that the metadata has three fields: user_address, raw_text, and carrier_address."

var example_page_2 = "An Example of Your Daily Work: Apprehension\n\nAnything look suspicious about the data on the previous page? That's right, this person is trying to commit a crime! A cyber terrorist crime! Specifically, it looks like this person's raw_text metadata is attemping to inflict an act of cyber terrorism. \
The correct arrest would be commanded as follows:\n\n                  bust\n\nThis indicates to the authorities that the raw_text field of this query has violated the Compatriot Act and that the citizen associated with the CNP should be arrested immediately.";
var example_page_3 = "An Example of Your Daily Work: Permission\n\nYou're probably wondering, what about non-violating metadata? That's what the permit command is for. If there ever is a piece of data that really isn't harmful, you're free to use permit to send it through. Remember, you can't arrest citizens who aren't guilty - that's against the law. We don't want the ethics committee drawing any attention, so I'd try to make sure you're correct before running a command.\
\n\nCongratulations! You are now equipped to help defend our nation against suspicious individuals. If you need any further guidance, please see the Reference Tab.";
var example_page_4 = "\n\n\n\n\n\n\n\n\n\n\n THIS PAGE REQUIRES ADDITIONAL PERMISSIONS TO VIEW";

var reference_page_1 ="                -DATA REFERENCE-  \n\nThe following pieces of information are identified by their required metadata fields.\n\nSMS - sent_at, raw text, carrier, location\n\nMMS - sent_at, raw_text, carrier, location, subject, format\n\nEMAIL - org_ip, rec_ip, raw_text, subject, sent_at, user_address, carrier_address\n\nSEARCH QUERY - user_address, raw_text, and carrier_address\n\nPHONE CALL - created_at, ended_at, number, carrier, location, channel\n\nFILE TRANSFER - org_ip, rec_ip, created_at, format, size\n\n";
var reference_page_2 ="               -METADATA REFERENCE-\n\ncarrier - Data service provider for information transfer. See reference for a list of secure carriers\n\ncarrier_address - The web server address of a service provider. All carrier extensions addresses must match with the user_address extension if present.\n\nchannel - Cable channel associated with telecommunications. Channels may only be one numeric digit, 0-9.\n\nformat - File format of text, image, or video file. See reference for a list of secure file formats\
\n\nidentifier\n\nlocation - Geographical location specifying the source of the data\n\nnumber - Phone number of associated citizens. Numbers take the form of X-XXX-XXX\n\norg_ip - ORIGINAL_INTERNET_PROTOCAL specifies the source of the data. All IP addresses must contain four numbers separated by periods. No number in an IP address can exceed 256\
\n\nprotection\n\nraw_text - Contains the contents of any transcribed or written data. Suspicious raw_text is grounds for arrest.\n\nrec_ip - RECIEVING_INTERNET_PROTOCAL specifies the intended destination of the data. All IP addresses must contain four numbers separated by periods. No number in an IP address can exceed 256.\n\nsent_at - Timestamp in the form of (DAY-MONTH-YEAR HOUR:MINUTE:SECOND) specifying the universal time at which the data was created. Timestamps are always compared to the current time.\
\n\nsize - Specifies the size (in MegaBits) of any file attached to the data. File sizes may not exceed limit 2MB for text messages, 20MB for emails, and 200MB for file or other transfers.\n\nsubject - In Internet or MMS messages, specifies the user-written tagline of a particular kind of data.\n\nuser_address - User address associated with data source. Address extension must match a secure carrier.";
var reference_page_3 ="             -SAFETY/SECURITY REFERENCE-\n\nSAFE CARRIERS: safecall, secureubc, lanix, sonviait\n\nSAFE FILE FORMATS: .pcd, .nta, .mvg, .anz, .sec, .mbw";
var reference_page_4 ="            -CONSOLE COMMAND REFERENCE-\
\n\nNote: some commands are only accessible during extraction or at the user's home screen.\
\n\nhello - outputs a string of text 'hello world' to the console.\
\n\nclear - clears current console display window.\
\n\npermission status - displays the current user's administrative permission status. \
\n\nopen manual - opens the training manual window regardless of the user's current screen.\
\n\nbust - Alerts local law enforcement that the current data that the current information is in violation of the Compatriot Act. May only be called during pipeline extraction.\
\n\npermit - Allows the current data to accepted. May only be called during pipeline extraction.\
\n\nbegin extraction - launches the Pipeline extraction executeable. Can only be completed once per day from the user's designated home screen.\
\n\ndecrypt [File/Application] [Subject/Name] - Decrypts an encrypted file or application for read-only use. Parameters are case-sensitive. Optional email subject line includes text beyond ':' indication. Command requires SYSTEM_ADMIN_2 permissions.\n\
\n\n";